name: Test Action
on:
  issue_comment:
    types: [created, edited]
jobs:
  first:
    name: First Job
    if: startsWith(github.event.comment.body, '/deploy')
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Reaction
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            "${{ github.event.comment.id }}" && github.rest.reactions.createForIssueComment({
              comment_id: "${{ github.event.comment.id }}",
              owner: context.repo.owner,
              repo: context.repo.repo,
              content: "eyes",
            })
  second:
    name: Second Job
    if: success()
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    needs: first
    permissions:
      issues: write
    steps:
      - name: Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              Successfully commented.
              `
            })